"""Build the deployable showcase site into showcase/_site/.

Assembles everything the live page needs from the repo's canonical artifacts,
so each document exists exactly once in version control:

  _site/index.html                  <- showcase/index.html, verbatim
  _site/assets/                     <- bridge chart (docs/), one-pager preview
                                       (showcase/), the four BU PDFs
                                       (output/bu_reports/)
  _site/reports/<name>.html         <- the six generated reports, converted
                                       from output/*.md with the same look as
                                       the main page and a back link

Served from the same origin, the PDFs open in the browser's viewer instead of
forcing a download, and the reports are readable pages rather than raw
markdown on GitHub.

Deploy: push the contents of _site/ to the gh-pages branch (see dev/NOTES.md).

Run: .venv/Scripts/python.exe showcase/build_site.py
"""

import shutil
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "showcase" / "_site"

ASSETS = [
    ROOT / "docs" / "variance_bridge_2025.png",
    ROOT / "showcase" / "production_onepager.png",
    ROOT / "output" / "bu_reports" / "production.pdf",
    ROOT / "output" / "bu_reports" / "marketing.pdf",
    ROOT / "output" / "bu_reports" / "digital.pdf",
    ROOT / "output" / "bu_reports" / "back_office.pdf",
]

# (source markdown, page title)
REPORTS = [
    ("executive_summary.md", "Executive summary"),
    ("board_pack.md", "Board pack (draft, pending sign-off)"),
    ("variance_report.md", "Variance analysis"),
    ("forecast_report.md", "Rolling forecast"),
    ("data_quality_report.md", "Data quality report"),
    ("qa_report.md", "QA review"),
]

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} &middot; EventCo FP&A demo</title>
<style>
  * {{ box-sizing: border-box; margin: 0; }}
  body {{
    background: #fcfcfb; color: #171715;
    font: 15.5px/1.65 "Segoe UI", system-ui, -apple-system, "Helvetica Neue", Arial, sans-serif;
  }}
  .wrap {{ max-width: 880px; margin: 0 auto; padding: 40px 24px 80px; }}
  .back {{
    display: inline-block; margin-bottom: 26px; font-size: 14px; font-weight: 600;
    color: #1d5aa6; text-decoration: none;
  }}
  .back:hover {{ text-decoration: underline; }}
  .doc-note {{
    font-size: 13px; color: #85837d; border: 1px solid #e5e4dd; background: #fff;
    border-radius: 8px; padding: 10px 14px; margin-bottom: 30px;
  }}
  h1 {{ font-size: 27px; line-height: 1.2; margin: 18px 0 12px; letter-spacing: -0.01em; }}
  h2 {{ font-size: 20px; margin: 30px 0 10px; }}
  h3 {{ font-size: 16.5px; margin: 22px 0 8px; }}
  p, li {{ color: #4f4e4a; margin-bottom: 10px; }}
  ul, ol {{ padding-left: 22px; margin-bottom: 12px; }}
  blockquote {{ border-left: 3px solid #2a78d6; padding: 4px 0 4px 16px; margin: 14px 0; }}
  blockquote p {{ color: #171715; }}
  code {{ font: 13px Consolas, "Cascadia Mono", Menlo, monospace; background: #f0efe9; padding: 1px 5px; border-radius: 4px; }}
  .tablewrap {{ overflow-x: auto; margin: 14px 0; border: 1px solid #e5e4dd; border-radius: 8px; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 13px; background: #fff; }}
  th, td {{ padding: 7px 10px; border-bottom: 1px solid #e5e4dd; text-align: left; vertical-align: top; }}
  th {{ color: #85837d; font-weight: 600; white-space: nowrap; }}
  tr:last-child td {{ border-bottom: none; }}
  hr {{ border: none; border-top: 1px solid #e5e4dd; margin: 26px 0; }}
  a {{ color: #1d5aa6; }}
</style>
</head>
<body>
<div class="wrap">
  <a class="back" href="../index.html">&larr; Back to the demo</a>
  <div class="doc-note">This document was generated by the close itself and is shown exactly as
  produced (draft status and all). How it fits in the workflow is explained on the main page.</div>
{body}
</div>
</body>
</html>
"""


def convert_report(md_path):
    text = md_path.read_text(encoding="utf-8")
    body = markdown.markdown(text, extensions=["tables"])
    # Wide report tables scroll inside their own container instead of
    # stretching the page.
    body = body.replace("<table>", '<div class="tablewrap"><table>')
    body = body.replace("</table>", "</table></div>")
    return body


def main():
    if SITE.exists():
        shutil.rmtree(SITE)
    (SITE / "assets").mkdir(parents=True)
    (SITE / "reports").mkdir()

    shutil.copyfile(ROOT / "showcase" / "index.html", SITE / "index.html")
    for src in ASSETS:
        shutil.copyfile(src, SITE / "assets" / src.name)
    for name, title in REPORTS:
        src = ROOT / "output" / name
        html = PAGE_TEMPLATE.format(title=title, body=convert_report(src))
        out = SITE / "reports" / (src.stem + ".html")
        out.write_text(html, encoding="utf-8")
        print(f"reports/{out.name} <- output/{name}")

    print(f"Site built in {SITE} "
          f"({sum(1 for _ in SITE.rglob('*') if _.is_file())} files)")


if __name__ == "__main__":
    main()
